# Dockerfile for building the stack

#See https://appsody.dev/docs/stacks/environment-variables for more information about each variable.

ENV APPSODY_MOUNTS= #Mount directories
ENV APPSODY_RUN="mvn -B -Dmaven.repo.local=/mvn/repository liberty:run"

ENV APPSODY_WATCH_DIR= #Directories to watch for changes in.
ENV APPSODY_WATCH_REGEX='^.*(.xml|.java|.properties)$'
ENV APPSODY_WATCH_IGNORE_DIR= #Directories to ignore changes in.


ENV APPSODY_INSTALL= #Optional command executed before RUN/TEST/DEBUG

ENV APPSODY_TEST_KILL=true

ENV APPSODY_DEBUG= #Command executed in 'debug' mode
ENV APPSODY_TEST_ON_CHANGE= #Command executed in 'test' mode when a change is detected.

ENV APPSODY_TEST= #Command executed in 'test' mode
